# Type: どのような種類であるか
- name: "type: epic"
  color: "1D76DB"
  description: "複数のタスクを束ねる親"
- name: "type: enhancement"
  color: "007bff"
  description: "新機能の追加や既存機能の改善"
- name: "type: bug"
  color: "d73a4a"
  description: "期待通りに動作しない不具合"
- name: "type: refactoring"
  color: "6f42c1"
  description: "コード品質を向上させる内部改善"

# Area: どの領域に関連するか
- name: "area: frontend"
  color: "28a745"
  description: "フロントエンドに関連"
- name: "area: backend"
  color: "24292e"
  description: "バックエンドに関連"
- name: "area: design"
  color: "db61a2"
  description: "UI/UXデザインに関連"
- name: "area: docs"
  color: "cfd8dc"
  description: "ドキュメントの作成や更新に関連"
- name: "area: infra"
  color: "8B4513"
  description: "開発や本番環境のインフラに関連"
- name: "area: security"
  color: "b60205"
  description: "セキュリティに関連する問題"

# Priority: 優先度
- name: "priority: critical"
  color: "b60205"
  description: "最優先で対応すべき"
- name: "priority: must"
  color: "fbca04"
  description: "リリースに必須"
- name: "priority: should"
  color: "fef2c0"
  description: "対応が推奨される改善"
- name: "priority: could"
  color: "f7f7f7"
  description: "必須ではない改善"

# Need: 必要なアクションや状態
- name: "need: attention"
  color: "ffc107"
  description: "慎重な作業やレビューが必要"
- name: "need: triage"
  color: "FF9800"
  description: "状況整理や優先度の判定が必要"
- name: "need: discussion"
  color: "84DEFF"
  description: "仕様や方針の議論が必要"
- name: "need: help"
  color: "0E8A16"
  description: "助けが必要な状態"
- name: "need: expert help"
  color: "00C4B3"
  description: "有識者や先輩の助けが必要"
