name: Backend CI

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  lint-build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Lint (golangci-lint)
        if: ${{ github.event_name != 'pull_request' || !contains(join(github.event.pull_request.labels.*.name, ','), 'skip-lint') }}
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          working-directory: backend

      - name: Skip notice
        if: ${{ github.event_name == 'pull_request' && contains(join(github.event.pull_request.labels.*.name, ','), 'skip-lint') }}
        run: echo "skip-lint を含むラベルが付与されているため golangci-lint をスキップしました"

      - name: Build
        run: go build ./...
