name: Frontend CI

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  lint-build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: frontend/package.json
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Format Check
        if: ${{ github.event_name != 'pull_request' || !contains(join(github.event.pull_request.labels.*.name, ','), 'skip-lint') }}
        run: npm run format:check

      - name: Lint / Format Skip notice
        if: ${{ github.event_name == 'pull_request' && contains(join(github.event.pull_request.labels.*.name, ','), 'skip-lint') }}
        run: echo "skip-lint を含むラベルが付与されているため format/lint をスキップしました"

      - name: Lint Check
        if: ${{ github.event_name != 'pull_request' || !contains(join(github.event.pull_request.labels.*.name, ','), 'skip-lint') }}
        run: npm run lint:ci

      - name: Build
        run: npm run build
